framework:
  default_locale: fr
  translator:
    default_path: '%kernel.project_dir%/translations'
    paths:
      - '%kernel.project_dir%/src/Modules/Project/translations'
    fallbacks:
      - fr
  #set_locale_from_accept_language: true
  #set_current_language_from_locale: true
  enabled_locales: [ 'fr', 'en' ]
